# Site settings
title: BarFly Ventures
email: it@barflyventures.com
description: > # this means to ignore newlines until "baseurl:"
  This is a BarFly Ventures team support website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://barflyventures.org" # the base hostname & protocol for your site
twitter_username: BarFlyIT
github_username:  BarFlyInfoTech
theme: jekyll-theme-midnight
include: ['_pages']
